
trigger:
- feature/AIDT-265-Build-pipeline-to-create-Linux-wheels

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip==23.0.1
    pip install wheel==0.38.4 --upgrade
    pip install setuptools==66 --upgrade
    pip install build
    pip install twine
    pip install keyring
    pip install artifacts-keyring
  displayName: 'Install build dependencies'

- script: |
    python -m pip install -e .[dev]
  displayName: 'Install Yawning-Titan'

- script: |
    cd docs
    make html
  displayName: 'Build Docs'

- script: |
    cd scripts
    sh copy_docs_to_gui_static.sh
  displayName: 'Copy built docs to gui static'

- script: |
    python -m build
  displayName: 'Build Yawning-Titan'

- task: TwineAuthenticate@1
  displayName: 'Twine Authenticate'
  inputs:
    artifactFeed: a6d6c871-7ecf-4c6e-9b67-157a3e02ce06/Yawning-Titan

- script: |
    python -m twine upload --verbose -r Yawning-Titan --config-file  $(PYPIRC_PATH) dist/*.whl
  displayName: 'Artifact Upload'
