
trigger:
- feature/AIDT-265-Build-pipeline-to-create-Linux-wheels

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'
  Python39:
    python.version: '3.9'
  Python310:
    python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install build
    pip install wheel
    pip install twine
    pip install pytest-azurepipelines
  displayName: 'Install build dependencies'

- script: |
    python setup.py bdist_wheel
  displayName: 'Build Yawning-Titan'


- task: TwineAuthenticate@1
  displayName: Twine Authenticate
  inputs:
    artifactFeed: YAWNING-TITAN/Yawning-Titan           #For an organization-scoped feed, artifactFeed: <FEED_NAME>.

- script: |
    python -m twine upload -r feedName --config-file $(PYPIRC_PATH) dist/*.whl
