blue:
  action_set:
    deceptive_nodes:
      max_number: 2
      new_node_on_relocate: true
      use: false
    do_nothing: false
    isolate_node: false
    make_node_safe:
      gives_random_vulnerability: false
      increases_vulnerability: false
      use: true
      vulnerability_change_during_node_patch: 0.4
    reconnect_node: false
    reduce_vulnerability: false
    restore_node: true
    scan: true
  attack_discovery:
    failed_attacks:
      chance:
        deceptive_node: 1
        standard_node: 1
      use: true
    succeeded_attacks:
      chance:
        deceptive_node: 1
        standard_node: 1
      use: true
    succeeded_attacks_unknown_comprimise:
      chance:
        deceptive_node: 1
        standard_node: 1
      use: true
  intrusion_discovery_chance:
    immediate: 0.5
    immediate_deceptive_node: 1
    on_scan: 1
    on_scan_deceptive_node: 1
blue_can_observe:
  attacked_nodes: true
  attacking_nodes: true
  average_vulnerability: false
  compromised_status: true
  graph_connectivity: true
  node_connections: true
  red_agent_skill: true
  special_nodes: true
  vulnerabilities: true
game_rules:
  blue_loss_condition:
    all_nodes_lost: false
    high_value_node_lost: true
    n_percent_nodes_lost:
      use: false
      value: 0.8
    target_node_lost: false
  grace_period_length: 0
  max_steps: 1000
  network_compatibility:
    entry_node_count:
      max: null
      min: null
      restrict: false
    high_value_node_count:
      max: null
      min: null
      restrict: false
    node_count:
      max: null
      min: 18
      restrict: false
miscellaneous:
  output_timestep_data_to_json: false
  random_seed: null
on_reset:
  choose_new_entry_nodes: true
  choose_new_high_value_nodes: true
  randomise_vulnerabilities: false
red:
  action_set:
    basic_attack:
      likelihood: 2
      use: true
    do_nothing:
      likelihood: 1
      use: true
    move:
      likelihood: 1
      use: false
    random_infect:
      chance: 0.1
      likelihood: 1
      use: false
    spread:
      chance: 0.1
      likelihood: 1
      use: false
    zero_day:
      days_required: 4
      start_amount: 1
      use: true
  agent_attack:
    always_succeeds: false
    attack_from:
      any_red_node: true
      only_red_agent_node: false
    ignores_defences: false
    skill:
      use: true
      value: 0.5
  natural_spreading:
    capable: true
    chance:
      to_connected_node: 0.05
      to_unconnected_node: 0
  target_mechanism:
    prioritise_connected_nodes: false
    prioritise_resilient_nodes: false
    prioritise_unconnected_nodes: false
    prioritise_vulnerable_nodes: false
    random: true
    target:
      always_choose_shortest_distance: true
      target: null
      use: false
rewards:
  end_rewards_are_multiplied_by_end_state: true
  for_loss: -100
  for_reaching_max_steps: 100
  function: standard_rewards
  reduce_negative_rewards_for_closer_fails: true
