name: build-sphinx-to-github-pages

env:
  GITHUB_ACTOR: methodsanalytics
  GITHUB_REPOSITORY: methodsanalytics/YAWNING-TITAN
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

on:
  push:
    branches: [feature/AIDT-99-update-documentation-readme-md-and-docs]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:

      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
        shell: bash
      - name: Show pwd and ls
        run: |
          pwd
          ls ./docs
      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "docs/build-sphinx-docs-to-github-pages.sh"
        shell: bash
