name: build-sphinx-to-github-pages

env:
  GITHUB_ACTOR: methodsanalytics
  GITHUB_REPOSITORY: methodsanalytics/YAWNING-TITAN
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

on:
  push:
    branches: [dev]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest

    steps:

      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          sudo apt-get update
          sudp apt-get install -y git
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt install python3.10 -y
          python -m pip install --upgrade pip
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash docs/build-sphinx-docs-to-github-pages.sh
